version: 0.2

phases:
  build:
    commands:
      - echo "Build started on `date`"
      - mvn clean package
  post_build:
    commands:
      - echo Build completed successfully
artifacts:
  files:
    - target/profile-andreas.jar
  discard-paths: yes